services:
  express-example-db:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - express-example-db:/var/lib/postgresql/data

  api:
    depends_on:
      - express-example-db
    env_file:
      - ./.env
    build:
      context: .
      target: production
    image: express:prod
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
volumes:
  express-example-db:
